name: crud1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  camera: ^0.8.1+7
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  permission_handler: ^8.1.4+2
  fluttertoast: ^8.0.8
  flutter_secure_storage: ^4.2.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.3+2
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  video_player: ^2.1.12
  dio: ^4.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  
  uses-material-design: true
  assets:
    - images/logo4HF.png
